#!/usr/bin/env python3
"""Generate a ready-to-run PRACTICE dump script from a registered layout, with
one Data.SAVE.Binary line per bank (no PRACTICE-side file parsing needed).

    python -m tools.emit_practice config/layouts/<KEY>.json --slot R7S1-01 > dump_M.cmm
"""
import argparse
import json
from pathlib import Path


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("layout")
    ap.add_argument("--slot", required=True, help="board slot, e.g. R7S1-01")
    ap.add_argument("--outdir", default="C:/uta/dumps")
    args = ap.parse_args()

    layout = json.loads(Path(args.layout).read_text())
    core = layout.get("core", "M")
    print("; AUTO-GENERATED by emit_practice.py — non-intrusive per-bank dump")
    print(f"; slot={args.slot} core={core} banks={len(layout['segments'])}")
    print("LOCAL &date &time")
    print('&date=FORMAT.UnixTime("%Y%m%d",CLOCK.UnixTime(),0)')
    print('&time=FORMAT.UnixTime("%H%M%S",CLOCK.UnixTime(),0)')
    for s in layout["segments"]:
        base, size = s["base"], s["size"]
        b8 = f"{base:08x}"
        tmp = f'"{args.outdir}/{args.slot}_{core}_&date._&time._{b8}.bank.tmp"'
        fin = f'"{args.outdir}/{args.slot}_{core}_&date._&time._{b8}.bank"'
        print(f"Data.SAVE.Binary {tmp} 0x{base:08x}++0x{size-1:08x}")
        print(f'OS.Command ren {tmp} {fin}')
    print("ENDDO")


if __name__ == "__main__":
    main()
