apiVersion: 1
datasources:
  - name: ClickHouse-UTA
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    jsonData:
      host: clickhouse
      port: 8123
      protocol: http
      username: default
      defaultDatabase: uta
    secureJsonData:
      password: "uta"
